### General project setup
general:
  productiveBranch: 'main'
  buildTool: 'mta'
  gitSshKeyCredentialsId: githubCredentialsId
  verbose: true

### Step-specific configuration
steps:
  handlePipelineStepErrors:
    failOnError: true

  artifactSetVersion:
    gitPushMode: 'NONE'
    commitVersion: false

  uiVeri5ExecuteTests:
    runOptions: ["--seleniumAddress=http://localhost:4444/wd/hub", "-v", "./app/admin/webapp/test/uiveri5/conf.js"]
    sidecarImage: "docker.wdf.sap.corp:50000/selenium/standalone-chrome"
    # runCommand: "/home/node/.npm-global/bin/uiveri5 --seleniumAddress=http://selenium:4444/wd/hub --base-url=https://cf-dts-integration-de-opensap-capire-bookshop-approuter.cfapps.eu10.hana.ondemand.com/app/fiori.html#manage-books -v"

  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfCredentialsId'
      org: 'cf-dts-integration-de'
      space: 'openSAP'

  pipelineStashFilesBeforeBuild:
    stashIncludes:
      pipelineConfigAndTests: '**/*'

### Stage-specific configuration
stages:
  'Central Build':
    buildExecute : true

  # 'Acceptance':
  #   cloudFoundryDeploy: false
  #   uiVeri5ExecuteTests: false

  # 'Release':
  #   cloudFoundryDeploy: true
