### General project setup
general:
  productiveBranch: 'main'
  buildTool: 'mta'
  gitSshKeyCredentialsId: githubCredentialsId
  verbose: true

### Step-specific configuration
steps:
  handlePipelineStepErrors:
    failOnError: true

  artifactSetVersion:
    gitPushMode: 'NONE'
    commitVersion: false

  uiVeri5ExecuteTests:
    runOptions: ["--seleniumAddress=http://localhost:4444/wd/hub", "./app/admin/webapp/test/uiveri5/conf.js"]
    # sidecarImage: "docker.wdf.sap.corp:50000/selenium/standalone-chrome"

  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfCredentialsId'
      org: 'cf-dts-integration-de'
      space: 'openSAP'

  # pipelineStashFilesBeforeBuild:
  #   stashIncludes:
  #     pipelineConfigAndTests: '**/*'

### Stage-specific configuration
stages:
  'Central Build':
    buildExecute : true

  # 'Acceptance':
  #   cloudFoundryDeploy: false
  #   uiVeri5ExecuteTests: false

  'Confirm':
    manualConfirmation: false

  'Release':
    cloudFoundryDeploy: false
