### General project setup
general:
  gitSshKeyCredentialsId: githubCredentialsId
  productiveBranch: 'main'
  buildTool: 'mta'
  # verbose: true

### Step-specific configuration
steps:
  # handlePipelineStepErrors:
  #   failOnError: true

  # artifactSetVersion:
  #   gitPushMode: 'NONE'
  #   commitVersion: false

  uiVeri5ExecuteTests:
    runOptions: ["--seleniumAddress=http://localhost:4444/wd/hub", "./app/admin/webapp/test/uiveri5/conf.js"]

  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfCredentialsId'
      org: '<YOUR_ORG>'
      space: '<YOUR_SPACE>'

### Stage-specific configuration
stages:
  'Central Build':
    buildExecute : true

  'Confirm':
    manualConfirmation: false

  'Release':
    cloudFoundryDeploy: false
